### ISSUE TITLE
Investigating Grok

### ISSUE THREAD

**Issue by glenrobson** [IIIF/htj2k#5]
Grok isn't supported by IIPimage yet so we can't test the decoding but this issue will investigate the encoding support. It looks to be supported in the documentation here:

https://github.com/GrokImageCompression/grok/wiki/3.-grk_compress#-m--mode-value

I've installed it using homebrew:

```
brew install grokj2k
```

**Comment by ruven** [comment]
I've just tested the latest version of Grok and it can indeed output valid HTJ2K jp2 files as well as of course raw code streams. No jph support yet though.
